version: "3"
services:
  mongo:
    image: mongo:3.4.5
    networks:
      - app-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.multi
    expose:
      - "8080"
    depends_on:
      - mongo
    networks:
      - app-net

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - app-net

networks:
  app-net:
