version: "3"
services:
  mongo:
    image: mongo:3.4.5
    networks:
      - app-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net

networks:
  app-net:
